spring:
  datasource:
    allen:
      jdbc-url: jdbc:mysql://localhost:3306/pandora?zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: select 1 from dual
      pool-name: allen-mysql
  redis:
    host: 127.0.0.1
    port: 6379
#    lettuce:
#      pool:
#        max-active: 5
#        min-idle: 3
#        max-wait: 3000ms


